import React, { useCallback, useState } from 'react';
import { useRouter, useFocusEffect } from 'expo-router';
import { Screen, Button, WorksheetCard, EmptyState, LoadingState, ErrorBoundary } from '@/components';
import { worksheetService } from '@/services';
import type { Worksheet } from '@/types';

function SheetsScreenContent() {
  const router = useRouter();
  const [worksheets, setWorksheets] = useState<Worksheet[] | null>(null);

  useFocusEffect(
    useCallback(() => {
      let active = true;
      worksheetService.list().then((items) => {
        if (active) setWorksheets(items ?? []);
      }).catch(() => {
        if (active) setWorksheets([]);
      });
      return () => { active = false; };
    }, []),
  );

  return (
    <Screen
      title="Worksheets"
      subtitle="Template scaffolds — you complete the content"
      headerRight={<Button title="New" icon="add" size="sm" onPress={() => router.push('/worksheet/create')} />}
    >
      {worksheets === null ? (
        <LoadingState label="Loading worksheets…" />
      ) : worksheets.length === 0 ? (
        <EmptyState
          icon="document-text-outline"
          title="No worksheets yet"
          message="Create a template worksheet to hand out in class. You fill in the questions — nothing is auto-generated by AI."
          actionLabel="New worksheet"
          onAction={() => router.push('/worksheet/create')}
        />
      ) : (
        worksheets.map((w) => (
          <WorksheetCard key={w.id} worksheet={w} onPress={() => router.push(`/worksheet/${w.id}`)} />
        ))
      )}
    </Screen>
  );
}

export default function SheetsScreen() {
  return (
    <ErrorBoundary fallbackTitle="Worksheets error">
      <SheetsScreenContent />
    </ErrorBoundary>
  );
}
