import type { Worksheet } from '@/types';

/**
 * Demo worksheet library. Questions are Hindi-medium Class 2 items. These are
 * illustrative demo worksheets, not generated by any AI model in Phase 1.
 */
export const WORKSHEETS: Worksheet[] = [
  {
    id: 'ws-add-1',
    title: 'जोड़ अभ्यास - २० तक',
    classGrade: 2,
    subject: 'Mathematics',
    topic: 'Addition up to 20',
    status: 'READY',
    createdAt: '2026-08-25T10:00:00.000Z',
    questions: [
      { id: 'q1', type: 'fill', prompt: '३ + २ = ____' },
      { id: 'q2', type: 'fill', prompt: '५ + ४ = ____' },
      {
        id: 'q3',
        type: 'mcq',
        prompt: '६ + ३ कितने होते हैं?',
        options: ['८', '९', '१०'],
        answer: '९',
      },
      { id: 'q4', type: 'short', prompt: 'चित्र में आम गिनकर कुल लिखो।' },
    ],
  },
  {
    id: 'ws-shapes-1',
    title: 'आकृतियाँ पहचानो',
    classGrade: 2,
    subject: 'Mathematics',
    topic: 'Basic shapes',
    status: 'DRAFT',
    createdAt: '2026-09-02T07:30:00.000Z',
    questions: [
      {
        id: 'q1',
        type: 'mcq',
        prompt: 'कौन सी चीज़ गोल है?',
        options: ['किताब', 'गेंद', 'डिब्बा'],
        answer: 'गेंद',
      },
      { id: 'q2', type: 'short', prompt: 'तीन कोनों वाली आकृति का नाम लिखो।' },
    ],
  },
];

export function getWorksheet(id: string): Worksheet | undefined {
  return WORKSHEETS.find((w) => w.id === id);
}
