import React, { useCallback, useState } from 'react';
import { View } from 'react-native';
import { useLocalSearchParams, useFocusEffect } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { Screen, AppText, Card, Button, StatusBadge, LoadingState, EmptyState, ErrorBoundary } from '@/components';
import { worksheetService } from '@/services';
import { colors, palette, spacing, radius, borderWidth } from '@/theme';
import type { QuestionType, Worksheet } from '@/types';

const TYPE_LABEL: Record<QuestionType, string> = {
  mcq: 'Multiple choice',
  short: 'Short answer',
  fill: 'Fill in the blank',
};

function WorksheetDetailContent() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const [worksheet, setWorksheet] = useState<Worksheet | null>(null);
  const [loading, setLoading] = useState(true);
  const [showAnswers, setShowAnswers] = useState(false);

  useFocusEffect(
    useCallback(() => {
      let active = true;
      setLoading(true);
      worksheetService.get(id ?? '').then((w) => {
        if (active) {
          setWorksheet(w);
          setLoading(false);
        }
      }).catch(() => {
        if (active) setLoading(false);
      });
      return () => { active = false; };
    }, [id]),
  );

  if (loading) {
    return (
      <Screen title="Worksheet" showBack>
        <LoadingState label="Loading worksheet…" />
      </Screen>
    );
  }

  if (!worksheet) {
    return (
      <Screen title="Worksheet" showBack>
        <EmptyState icon="document-text-outline" title="Worksheet not found" message="This worksheet is no longer available." />
      </Screen>
    );
  }

  const hasAnswers = worksheet.questions.some((q) => q.answer);

  return (
    <Screen
      title={worksheet.title}
      showBack
      headerRight={
        hasAnswers ? (
          <Button
            title={showAnswers ? 'Hide keys' : 'Answers'}
            icon={showAnswers ? 'eye-off-outline' : 'eye-outline'}
            variant="outline"
            size="sm"
            onPress={() => setShowAnswers((s) => !s)}
          />
        ) : undefined
      }
    >
      <View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: spacing.xs }}>
        <StatusBadge label={worksheet.status === 'READY' ? 'Ready' : 'Draft'} tone={worksheet.status === 'READY' ? 'success' : 'processing'} />
        <StatusBadge label={`Class ${worksheet.classGrade}`} tone="neutral" />
        <StatusBadge label={worksheet.subject} tone="neutral" />
      </View>

      <AppText variant="body" color={colors.textMuted} style={{ marginTop: spacing.md }}>
        {worksheet.topic}
      </AppText>

      {/* Honesty note: template, not AI-generated */}
      <Card backgroundColor={palette.sand} shadowSize="sm" style={{ marginTop: spacing.lg }}>
        <View style={{ flexDirection: 'row', gap: spacing.sm, alignItems: 'flex-start' }}>
          <Ionicons name="construct-outline" size={18} color={colors.text} />
          <AppText variant="bodySmall" style={{ flex: 1 }}>
            This is a template scaffold you can edit and print — the questions are illustrative, not
            generated by an AI model.
          </AppText>
        </View>
      </Card>

      <AppText variant="h3" style={{ marginTop: spacing.xl, marginBottom: spacing.md }}>
        {worksheet.questions.length} questions
      </AppText>

      <View style={{ gap: spacing.md }}>
        {worksheet.questions.map((q, index) => (
          <Card key={q.id} shadowSize="sm">
            <View style={{ flexDirection: 'row', gap: spacing.md }}>
              <View
                style={{
                  width: 30,
                  height: 30,
                  borderRadius: radius.sm,
                  borderWidth: borderWidth.thin,
                  borderColor: colors.border,
                  backgroundColor: colors.surfaceAlt,
                  alignItems: 'center',
                  justifyContent: 'center',
                }}
              >
                <AppText variant="bodyStrong">{index + 1}</AppText>
              </View>
              <View style={{ flex: 1 }}>
                <StatusBadge label={TYPE_LABEL[q.type]} tone="neutral" style={{ marginBottom: spacing.sm }} />
                <AppText variant="body">{q.prompt}</AppText>

                {q.type === 'mcq' && q.options ? (
                  <View style={{ marginTop: spacing.sm, gap: spacing.xs }}>
                    {q.options.map((opt, i) => {
                      const isAnswer = showAnswers && q.answer === opt;
                      return (
                        <View
                          key={i}
                          style={{
                            flexDirection: 'row',
                            alignItems: 'center',
                            gap: spacing.sm,
                            paddingVertical: spacing.xs,
                            paddingHorizontal: spacing.sm,
                            borderWidth: borderWidth.thin,
                            borderColor: isAnswer ? colors.success : colors.border,
                            borderRadius: radius.sm,
                            backgroundColor: isAnswer ? palette.sand : colors.surface,
                          }}
                        >
                          <AppText variant="bodySmall" color={colors.textMuted}>
                            {String.fromCharCode(65 + i)}.
                          </AppText>
                          <AppText variant="body" style={{ flex: 1 }}>
                            {opt}
                          </AppText>
                          {isAnswer ? <Ionicons name="checkmark-circle" size={18} color={colors.success} /> : null}
                        </View>
                      );
                    })}
                  </View>
                ) : (
                  <View
                    style={{
                      marginTop: spacing.sm,
                      height: borderWidth.thin,
                      backgroundColor: colors.border,
                    }}
                  />
                )}

                {showAnswers && q.answer && q.type !== 'mcq' ? (
                  <AppText variant="bodySmall" color={colors.success} style={{ marginTop: spacing.sm }}>
                    Answer: {q.answer}
                  </AppText>
                ) : null}
              </View>
            </View>
          </Card>
        ))}
      </View>
    </Screen>
  );
}

export default function WorksheetDetailScreen() {
  return (
    <ErrorBoundary fallbackTitle="Worksheet error">
      <WorksheetDetailContent />
    </ErrorBoundary>
  );
}
